apiVersion: v1
kind: Pod
metadata:
 name: podemptydir
spec:
 containers:
  - name: monnginx
    image: nginx
    ports:
    - containerPort: 80
    volumeMounts:
    - mountPath: /usr/share/nginx/html
      name: monvolume
  - name: monalpine
    image: alpine
    command: ['sh', '-c', 'while true; do date >/commejeveux/index.html; sleep 1; done' ]
    volumeMounts:
    - mountPath: /commejeveux/
      name: monvolume
 volumes:
   - name: monvolume
     emptyDir: {}
